import Head from 'next/head'
import HomePage from '../components/Home';
import styles from '../styles/Home.module.css'

export default function Home({data,topBlogs,topWriters}) {
	
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
			<HomePage blogs={data} topBlogs={topBlogs} topWriters={topWriters}/>
    </div>
  )
}

export async function getStaticProps (){
	const [res, res2,res3] = await Promise.all([
		fetch('http://localhost:4000/blog'),
		fetch('http://localhost:4000/blog/top-blogs'),
		fetch('http://localhost:4000/user/top-users')
	])
	// const res = await fetch('http://localhost:4000/blog')
	// const res2 = await fetch('http://localhost:4000/blog/top-blogs')
	const [data, topBlogs,topWriters] = await Promise.all([
		res.json(),
		res2.json(),
		res3.json()
	])
	// const data = await res.json()
	// const topBlogs = await res2.json()
	return{
		props : {
			data,topBlogs,topWriters
		}
	}
}